### ISSUE TITLE
This doesn't work with the dark theme

### ISSUE THREAD

**Issue by codingmatty** [BrainMaestro/cerebro-weather#1]
This renders cerebro completely unusable if you have the dark theme enabled.

<img width="657" alt="screen shot 2017-03-30 at 5 42 22 pm" src="https://cloud.githubusercontent.com/assets/6119312/24529302/59b4b0d2-1570-11e7-8034-d947e2c5afaf.png">

**Comment by BrainMaestro** [comment]
Hmm, I wonder why that's happening. Would you like to try fixing it? If not, I'll get to it over the weekend. Thanks for reporting

**Comment by BrainMaestro** [comment]
Hey, I finally got around to fixing it. Just pull the new update and it should be good.

What it looks like: 
![screen shot 2017-04-04 at 12 29 10 pm](https://cloud.githubusercontent.com/assets/1738373/24654625/656b3c64-1932-11e7-9bef-0259adb781d5.png).

I'll close this now. Let me know if there are any other issues.

**Comment by codingmatty** [comment]
I can confirm that the theme fix is good 👍
