### ISSUE TITLE
Better handling for locations with no results

### ISSUE THREAD

**Issue by peachesthefruit** [BrainMaestro/cerebro-weather#4]
I often get `TypeError: Cannot read property 'woeid' of undefined` in the developer console. This is occurring when the weather api returns an empty array of locations. The head function in the snippet below returns undefined which leads to the eventual TypeError. The preview also gets stuck at 'Loading...'. It might be best to not show any Cerebro results when there are no locations or give a different display.

    export const getWeather = city => (
      searchCity(city)
        .then(head)
        .then(prop('woeid'))
        .then(getCityWeather)
    )

**Comment by BrainMaestro** [comment]
@jrjohnson1231. Yeah any form of error handling has been missing for a while. Was hoping someone would notice and open a PR. Are you interested in doing one? Should be a relatively easy fix.

**Comment by peachesthefruit** [comment]
Yeah I will start working on this PR

**Comment by BrainMaestro** [comment]
That's great!

**Comment by peachesthefruit** [comment]
PR: #5
