### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Stanzilla** [BrainMaestro/cerebro-weather#6]
Uncaught (in promise) TypeError: Cannot read property 'woeid' of undefined
    at C:\Users\Benjamin\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-weather\dist\index.js:1
    at C:\Users\Benjamin\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-weather\dist\index.js:1
    at re (C:\Users\Benjamin\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-weather\dist\index.js:1)

**Comment by BrainMaestro** [comment]
Yeah that happens when the city was not found. Do you want to try fixing it? Should be a simple fix
